### ISSUE TITLE
font-face support

### ISSUE THREAD

**Issue by ekazakov14** [AiverReaver/Laravel-Vue-Typescript#2]
ERROR in ./resources/fonts/Nunito/subset-Nunito-Regular.eot 1:0
    Module parse failed: Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./resources/sass/app.scss (./node_modules/css-loader!./node_modules/postcss-loader/src!./node_modules/sass-loader/lib/loader.js!./resources/sass/app.scss) 7:4535-4587 7:4618-4670

im fix this problem, accept my pull request https://github.com/AiverReaver/Laravel-Vue-Typescript/pull/1

**Comment by AiverReaver** [comment]
Ohh I forget to add font-face support.
thanks for contribution
